/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_Bienvenue (void);
GtkWidget* create_Ajouter_utilisateur (void);
GtkWidget* create_Afficher_utilisatuer (void);
GtkWidget* create_Modifer_utilisateur (void);
GtkWidget* create_Rechercher_utilisateur (void);
GtkWidget* create_Supprimer_utilisateur (void);
GtkWidget* create_confirmation (void);
GtkWidget* create_nbr_niveau (void);
