/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_Bienvenue (void)
{
  GtkWidget *Bienvenue;
  GtkWidget *fixed1;
  GtkWidget *label1;
  GtkWidget *button_afficher_utilisateurFK;
  GtkWidget *button_modifier_utilisateurFK;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *button_supprimer_utilisateurFK;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label4;
  GtkWidget *button_rechercher_utilisateurFK;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *button_ajouter_utilisateurFK;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label2;
  GtkWidget *button_calculer_niveauFK;

  Bienvenue = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Bienvenue), _("Bienvenue"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (Bienvenue), fixed1);

  label1 = gtk_label_new (_("Bienvenue"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 300, 64);
  gtk_widget_set_size_request (label1, 360, 48);

  button_afficher_utilisateurFK = gtk_button_new_with_mnemonic (_("Afficher les Utilisateurs"));
  gtk_widget_show (button_afficher_utilisateurFK);
  gtk_fixed_put (GTK_FIXED (fixed1), button_afficher_utilisateurFK, 300, 600);
  gtk_widget_set_size_request (button_afficher_utilisateurFK, 450, 40);

  button_modifier_utilisateurFK = gtk_button_new ();
  gtk_widget_show (button_modifier_utilisateurFK);
  gtk_fixed_put (GTK_FIXED (fixed1), button_modifier_utilisateurFK, 300, 500);
  gtk_widget_set_size_request (button_modifier_utilisateurFK, 450, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_modifier_utilisateurFK), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("Modifier un Utilisateur"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox4), label5, FALSE, FALSE, 0);

  button_supprimer_utilisateurFK = gtk_button_new ();
  gtk_widget_show (button_supprimer_utilisateurFK);
  gtk_fixed_put (GTK_FIXED (fixed1), button_supprimer_utilisateurFK, 300, 400);
  gtk_widget_set_size_request (button_supprimer_utilisateurFK, 450, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_supprimer_utilisateurFK), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Supprimer un Utilisateur"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  button_rechercher_utilisateurFK = gtk_button_new ();
  gtk_widget_show (button_rechercher_utilisateurFK);
  gtk_fixed_put (GTK_FIXED (fixed1), button_rechercher_utilisateurFK, 300, 300);
  gtk_widget_set_size_request (button_rechercher_utilisateurFK, 450, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (button_rechercher_utilisateurFK), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("Rechercher un Utilisateur"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  button_ajouter_utilisateurFK = gtk_button_new ();
  gtk_widget_show (button_ajouter_utilisateurFK);
  gtk_fixed_put (GTK_FIXED (fixed1), button_ajouter_utilisateurFK, 300, 200);
  gtk_widget_set_size_request (button_ajouter_utilisateurFK, 450, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (button_ajouter_utilisateurFK), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label2 = gtk_label_new_with_mnemonic (_("Ajouter un Utilisateur"));
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox1), label2, FALSE, FALSE, 0);

  button_calculer_niveauFK = gtk_button_new_with_mnemonic (_("Nombre d'etudiant par niveau"));
  gtk_widget_show (button_calculer_niveauFK);
  gtk_fixed_put (GTK_FIXED (fixed1), button_calculer_niveauFK, 300, 700);
  gtk_widget_set_size_request (button_calculer_niveauFK, 450, 40);

  g_signal_connect ((gpointer) button_afficher_utilisateurFK, "clicked",
                    G_CALLBACK (on_button_afficher_utilisateurFK_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_modifier_utilisateurFK, "clicked",
                    G_CALLBACK (on_button_modifier_utilisateurFK_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_supprimer_utilisateurFK, "clicked",
                    G_CALLBACK (on_button_supprimer_utilisateur_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_rechercher_utilisateurFK, "clicked",
                    G_CALLBACK (on_button_rechercher_utilisateur_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_ajouter_utilisateurFK, "clicked",
                    G_CALLBACK (on_button_ajouter_utilisateurFK_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_calculer_niveauFK, "clicked",
                    G_CALLBACK (on_button_calculer_niveauFK_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Bienvenue, Bienvenue, "Bienvenue");
  GLADE_HOOKUP_OBJECT (Bienvenue, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (Bienvenue, label1, "label1");
  GLADE_HOOKUP_OBJECT (Bienvenue, button_afficher_utilisateurFK, "button_afficher_utilisateurFK");
  GLADE_HOOKUP_OBJECT (Bienvenue, button_modifier_utilisateurFK, "button_modifier_utilisateurFK");
  GLADE_HOOKUP_OBJECT (Bienvenue, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Bienvenue, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Bienvenue, image4, "image4");
  GLADE_HOOKUP_OBJECT (Bienvenue, label5, "label5");
  GLADE_HOOKUP_OBJECT (Bienvenue, button_supprimer_utilisateurFK, "button_supprimer_utilisateurFK");
  GLADE_HOOKUP_OBJECT (Bienvenue, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (Bienvenue, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (Bienvenue, image3, "image3");
  GLADE_HOOKUP_OBJECT (Bienvenue, label4, "label4");
  GLADE_HOOKUP_OBJECT (Bienvenue, button_rechercher_utilisateurFK, "button_rechercher_utilisateurFK");
  GLADE_HOOKUP_OBJECT (Bienvenue, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (Bienvenue, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (Bienvenue, image2, "image2");
  GLADE_HOOKUP_OBJECT (Bienvenue, label3, "label3");
  GLADE_HOOKUP_OBJECT (Bienvenue, button_ajouter_utilisateurFK, "button_ajouter_utilisateurFK");
  GLADE_HOOKUP_OBJECT (Bienvenue, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (Bienvenue, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (Bienvenue, image1, "image1");
  GLADE_HOOKUP_OBJECT (Bienvenue, label2, "label2");
  GLADE_HOOKUP_OBJECT (Bienvenue, button_calculer_niveauFK, "button_calculer_niveauFK");

  return Bienvenue;
}

GtkWidget*
create_Ajouter_utilisateur (void)
{
  GtkWidget *Ajouter_utilisateur;
  GtkWidget *fixed2;
  GtkWidget *entry1FK;
  GtkWidget *entry2FK;
  GtkWidget *entry3FK;
  GtkWidget *entry4FK;
  GtkObject *spinbutton1FK_adj;
  GtkWidget *spinbutton1FK;
  GtkWidget *label6;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *label13;
  GtkWidget *label14;
  GtkWidget *checkbutton1FK;
  GtkWidget *checkbutton2FK;
  GtkWidget *checkbutton3FK;
  GtkWidget *radiobutton1FK;
  GSList *radiobutton1FK_group = NULL;
  GtkWidget *radiobutton2FK;
  GtkWidget *button_valider1FK;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label16;
  GtkWidget *button_retourner1FK;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label15;
  GtkWidget *combobox1FK;

  Ajouter_utilisateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Ajouter_utilisateur), _("Ajouter un nouveau Utilisateur"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (Ajouter_utilisateur), fixed2);

  entry1FK = gtk_entry_new ();
  gtk_widget_show (entry1FK);
  gtk_fixed_put (GTK_FIXED (fixed2), entry1FK, 350, 150);
  gtk_widget_set_size_request (entry1FK, 300, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1FK), 8226);

  entry2FK = gtk_entry_new ();
  gtk_widget_show (entry2FK);
  gtk_fixed_put (GTK_FIXED (fixed2), entry2FK, 350, 250);
  gtk_widget_set_size_request (entry2FK, 300, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry2FK), 8226);

  entry3FK = gtk_entry_new ();
  gtk_widget_show (entry3FK);
  gtk_fixed_put (GTK_FIXED (fixed2), entry3FK, 350, 350);
  gtk_widget_set_size_request (entry3FK, 300, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry3FK), 8226);

  entry4FK = gtk_entry_new ();
  gtk_widget_show (entry4FK);
  gtk_fixed_put (GTK_FIXED (fixed2), entry4FK, 350, 450);
  gtk_widget_set_size_request (entry4FK, 300, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry4FK), 8226);

  spinbutton1FK_adj = gtk_adjustment_new (17, 17, 80, 1, 10, 10);
  spinbutton1FK = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton1FK_adj), 1, 0);
  gtk_widget_show (spinbutton1FK);
  gtk_fixed_put (GTK_FIXED (fixed2), spinbutton1FK, 350, 550);
  gtk_widget_set_size_request (spinbutton1FK, 112, 40);

  label6 = gtk_label_new (_("Nouveau Utilisateur"));
  gtk_widget_show (label6);
  gtk_fixed_put (GTK_FIXED (fixed2), label6, 350, 50);
  gtk_widget_set_size_request (label6, 344, 40);

  label7 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed2), label7, 100, 150);
  gtk_widget_set_size_request (label7, 256, 40);

  label8 = gtk_label_new (_("Nom"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed2), label8, 100, 250);
  gtk_widget_set_size_request (label8, 232, 40);

  label9 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed2), label9, 100, 350);
  gtk_widget_set_size_request (label9, 224, 40);

  label10 = gtk_label_new (_("Cin"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed2), label10, 100, 450);
  gtk_widget_set_size_request (label10, 168, 40);

  label11 = gtk_label_new (_("Age"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed2), label11, 100, 550);
  gtk_widget_set_size_request (label11, 176, 40);

  label12 = gtk_label_new (_("Niveau"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed2), label12, 100, 650);
  gtk_widget_set_size_request (label12, 240, 32);

  label13 = gtk_label_new (_("Role"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed2), label13, 100, 750);
  gtk_widget_set_size_request (label13, 168, 40);

  label14 = gtk_label_new (_("Sexe"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 100, 850);
  gtk_widget_set_size_request (label14, 168, 40);

  checkbutton1FK = gtk_check_button_new_with_mnemonic (_("Etudiant"));
  gtk_widget_show (checkbutton1FK);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton1FK, 344, 750);
  gtk_widget_set_size_request (checkbutton1FK, 211, 38);

  checkbutton2FK = gtk_check_button_new_with_mnemonic (_("Enseignant"));
  gtk_widget_show (checkbutton2FK);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton2FK, 584, 750);
  gtk_widget_set_size_request (checkbutton2FK, 211, 38);

  checkbutton3FK = gtk_check_button_new_with_mnemonic (_("Agent"));
  gtk_widget_show (checkbutton3FK);
  gtk_fixed_put (GTK_FIXED (fixed2), checkbutton3FK, 808, 750);
  gtk_widget_set_size_request (checkbutton3FK, 211, 38);

  radiobutton1FK = gtk_radio_button_new_with_mnemonic (NULL, _("Male"));
  gtk_widget_show (radiobutton1FK);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton1FK, 368, 850);
  gtk_widget_set_size_request (radiobutton1FK, 202, 38);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton1FK), radiobutton1FK_group);
  radiobutton1FK_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton1FK));

  radiobutton2FK = gtk_radio_button_new_with_mnemonic (NULL, _("Femelle"));
  gtk_widget_show (radiobutton2FK);
  gtk_fixed_put (GTK_FIXED (fixed2), radiobutton2FK, 640, 850);
  gtk_widget_set_size_request (radiobutton2FK, 202, 38);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton2FK), radiobutton1FK_group);
  radiobutton1FK_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton2FK));

  button_valider1FK = gtk_button_new ();
  gtk_widget_show (button_valider1FK);
  gtk_fixed_put (GTK_FIXED (fixed2), button_valider1FK, 600, 950);
  gtk_widget_set_size_request (button_valider1FK, 300, 40);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_valider1FK), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label16 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label16);
  gtk_box_pack_start (GTK_BOX (hbox6), label16, FALSE, FALSE, 0);

  button_retourner1FK = gtk_button_new ();
  gtk_widget_show (button_retourner1FK);
  gtk_fixed_put (GTK_FIXED (fixed2), button_retourner1FK, 250, 950);
  gtk_widget_set_size_request (button_retourner1FK, 300, 40);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_retourner1FK), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label15 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label15);
  gtk_box_pack_start (GTK_BOX (hbox5), label15, FALSE, FALSE, 0);

  combobox1FK = gtk_combo_box_new_text ();
  gtk_widget_show (combobox1FK);
  gtk_fixed_put (GTK_FIXED (fixed2), combobox1FK, 350, 650);
  gtk_widget_set_size_request (combobox1FK, 240, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1FK), _("1 \303\250re"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1FK), _("2 \303\250me"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1FK), _("3 \303\250me"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1FK), _("4 \303\250me"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1FK), _("5 \303\250me"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox1FK), _("999"));

  g_signal_connect ((gpointer) checkbutton1FK, "toggled",
                    G_CALLBACK (on_checkbutton1FK_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton2FK, "toggled",
                    G_CALLBACK (on_checkbutton2FK_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton3FK, "toggled",
                    G_CALLBACK (on_checkbutton3FK_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton1FK, "toggled",
                    G_CALLBACK (on_radiobutton1FK_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton2FK, "toggled",
                    G_CALLBACK (on_radiobutton2FK_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_valider1FK, "clicked",
                    G_CALLBACK (on_button_valider1FK_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retourner1FK, "clicked",
                    G_CALLBACK (on_button_retourner1FK_activate),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Ajouter_utilisateur, Ajouter_utilisateur, "Ajouter_utilisateur");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, entry1FK, "entry1FK");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, entry2FK, "entry2FK");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, entry3FK, "entry3FK");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, entry4FK, "entry4FK");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, spinbutton1FK, "spinbutton1FK");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, label6, "label6");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, label7, "label7");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, label8, "label8");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, label9, "label9");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, label10, "label10");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, label11, "label11");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, label12, "label12");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, label13, "label13");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, label14, "label14");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, checkbutton1FK, "checkbutton1FK");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, checkbutton2FK, "checkbutton2FK");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, checkbutton3FK, "checkbutton3FK");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, radiobutton1FK, "radiobutton1FK");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, radiobutton2FK, "radiobutton2FK");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, button_valider1FK, "button_valider1FK");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, image6, "image6");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, label16, "label16");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, button_retourner1FK, "button_retourner1FK");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, image5, "image5");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, label15, "label15");
  GLADE_HOOKUP_OBJECT (Ajouter_utilisateur, combobox1FK, "combobox1FK");

  return Ajouter_utilisateur;
}

GtkWidget*
create_Afficher_utilisatuer (void)
{
  GtkWidget *Afficher_utilisatuer;
  GtkWidget *fixed3;
  GtkWidget *treeview1;
  GtkWidget *button_retourner2FK;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label17;

  Afficher_utilisatuer = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Afficher_utilisatuer), _("Afficher les Utilisateurs"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Afficher_utilisatuer), fixed3);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed3), treeview1, 80, 96);
  gtk_widget_set_size_request (treeview1, 848, 408);

  button_retourner2FK = gtk_button_new ();
  gtk_widget_show (button_retourner2FK);
  gtk_fixed_put (GTK_FIXED (fixed3), button_retourner2FK, 144, 560);
  gtk_widget_set_size_request (button_retourner2FK, 256, 40);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (button_retourner2FK), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label17 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label17);
  gtk_box_pack_start (GTK_BOX (hbox7), label17, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_retourner2FK, "clicked",
                    G_CALLBACK (on_button_retourner2FK_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Afficher_utilisatuer, Afficher_utilisatuer, "Afficher_utilisatuer");
  GLADE_HOOKUP_OBJECT (Afficher_utilisatuer, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Afficher_utilisatuer, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Afficher_utilisatuer, button_retourner2FK, "button_retourner2FK");
  GLADE_HOOKUP_OBJECT (Afficher_utilisatuer, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Afficher_utilisatuer, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Afficher_utilisatuer, image7, "image7");
  GLADE_HOOKUP_OBJECT (Afficher_utilisatuer, label17, "label17");

  return Afficher_utilisatuer;
}

GtkWidget*
create_Modifer_utilisateur (void)
{
  GtkWidget *Modifer_utilisateur;
  GtkWidget *fixed4;
  GtkWidget *entry5;
  GtkWidget *entry6;
  GtkWidget *entry7;
  GtkWidget *entry8;
  GtkObject *spinbutton2_adj;
  GtkWidget *spinbutton2;
  GtkWidget *label18;
  GtkWidget *radiobutton3FK;
  GSList *radiobutton3FK_group = NULL;
  GtkWidget *radiobutton4FK;
  GtkWidget *checkbutton4FK;
  GtkWidget *checkbutton5FK;
  GtkWidget *checkbutton6FK;
  GtkWidget *label19;
  GtkWidget *label20;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkWidget *label23;
  GtkWidget *label25;
  GtkWidget *label24;
  GtkWidget *label26;
  GtkWidget *button_retourner3FK;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label27;
  GtkWidget *button_valider2FK;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label28;
  GtkWidget *combobox2;

  Modifer_utilisateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Modifer_utilisateur), _("window4"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (Modifer_utilisateur), fixed4);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_fixed_put (GTK_FIXED (fixed4), entry5, 400, 150);
  gtk_widget_set_size_request (entry5, 300, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry5), 8226);

  entry6 = gtk_entry_new ();
  gtk_widget_show (entry6);
  gtk_fixed_put (GTK_FIXED (fixed4), entry6, 400, 250);
  gtk_widget_set_size_request (entry6, 300, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry6), 8226);

  entry7 = gtk_entry_new ();
  gtk_widget_show (entry7);
  gtk_fixed_put (GTK_FIXED (fixed4), entry7, 400, 350);
  gtk_widget_set_size_request (entry7, 300, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry7), 8226);

  entry8 = gtk_entry_new ();
  gtk_widget_show (entry8);
  gtk_fixed_put (GTK_FIXED (fixed4), entry8, 400, 450);
  gtk_widget_set_size_request (entry8, 300, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry8), 8226);

  spinbutton2_adj = gtk_adjustment_new (17, 17, 80, 1, 10, 10);
  spinbutton2 = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton2_adj), 1, 0);
  gtk_widget_show (spinbutton2);
  gtk_fixed_put (GTK_FIXED (fixed4), spinbutton2, 400, 550);
  gtk_widget_set_size_request (spinbutton2, 81, 44);

  label18 = gtk_label_new (_("Modifer un Utilisateur"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 400, 50);
  gtk_widget_set_size_request (label18, 296, 32);

  radiobutton3FK = gtk_radio_button_new_with_mnemonic (NULL, _("Male"));
  gtk_widget_show (radiobutton3FK);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton3FK, 432, 850);
  gtk_widget_set_size_request (radiobutton3FK, 202, 38);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton3FK), radiobutton3FK_group);
  radiobutton3FK_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton3FK));

  radiobutton4FK = gtk_radio_button_new_with_mnemonic (NULL, _("Femelle"));
  gtk_widget_show (radiobutton4FK);
  gtk_fixed_put (GTK_FIXED (fixed4), radiobutton4FK, 720, 850);
  gtk_widget_set_size_request (radiobutton4FK, 202, 38);
  gtk_radio_button_set_group (GTK_RADIO_BUTTON (radiobutton4FK), radiobutton3FK_group);
  radiobutton3FK_group = gtk_radio_button_get_group (GTK_RADIO_BUTTON (radiobutton4FK));

  checkbutton4FK = gtk_check_button_new_with_mnemonic (_("Etudiant"));
  gtk_widget_show (checkbutton4FK);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton4FK, 384, 750);
  gtk_widget_set_size_request (checkbutton4FK, 211, 38);

  checkbutton5FK = gtk_check_button_new_with_mnemonic (_("Enseingant"));
  gtk_widget_show (checkbutton5FK);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton5FK, 640, 750);
  gtk_widget_set_size_request (checkbutton5FK, 211, 38);

  checkbutton6FK = gtk_check_button_new_with_mnemonic (_("Agent"));
  gtk_widget_show (checkbutton6FK);
  gtk_fixed_put (GTK_FIXED (fixed4), checkbutton6FK, 896, 750);
  gtk_widget_set_size_request (checkbutton6FK, 211, 38);

  label19 = gtk_label_new (_("Identifiant"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 100, 150);
  gtk_widget_set_size_request (label19, 300, 40);

  label20 = gtk_label_new (_("Nouveau Nom"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 100, 250);
  gtk_widget_set_size_request (label20, 300, 40);

  label21 = gtk_label_new (_("Nouveau Prenom"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 100, 350);
  gtk_widget_set_size_request (label21, 300, 40);

  label22 = gtk_label_new (_("Nouveau Cin"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed4), label22, 100, 450);
  gtk_widget_set_size_request (label22, 300, 40);

  label23 = gtk_label_new (_("Nouveau Age"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed4), label23, 100, 550);
  gtk_widget_set_size_request (label23, 300, 40);

  label25 = gtk_label_new (_("Nouveau Niveau"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed4), label25, 100, 650);
  gtk_widget_set_size_request (label25, 300, 40);

  label24 = gtk_label_new (_("Nouveau Role"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed4), label24, 100, 750);
  gtk_widget_set_size_request (label24, 300, 40);

  label26 = gtk_label_new (_("Nouveau Sexe"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed4), label26, 100, 850);
  gtk_widget_set_size_request (label26, 300, 40);

  button_retourner3FK = gtk_button_new ();
  gtk_widget_show (button_retourner3FK);
  gtk_fixed_put (GTK_FIXED (fixed4), button_retourner3FK, 250, 950);
  gtk_widget_set_size_request (button_retourner3FK, 300, 40);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (button_retourner3FK), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox8), label27, FALSE, FALSE, 0);

  button_valider2FK = gtk_button_new ();
  gtk_widget_show (button_valider2FK);
  gtk_fixed_put (GTK_FIXED (fixed4), button_valider2FK, 696, 950);
  gtk_widget_set_size_request (button_valider2FK, 300, 40);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (button_valider2FK), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox9), label28, FALSE, FALSE, 0);

  combobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (combobox2);
  gtk_fixed_put (GTK_FIXED (fixed4), combobox2, 400, 650);
  gtk_widget_set_size_request (combobox2, 232, 48);
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("1 \303\250re"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("2 \303\250me"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("3 \303\250me"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("4 \303\250me"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("5 \303\250me"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (combobox2), _("999"));

  g_signal_connect ((gpointer) radiobutton3FK, "toggled",
                    G_CALLBACK (on_radiobutton3FK_toggled),
                    NULL);
  g_signal_connect ((gpointer) radiobutton4FK, "toggled",
                    G_CALLBACK (on_radiobutton4FK_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton4FK, "toggled",
                    G_CALLBACK (on_checkbutton4FK_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton5FK, "toggled",
                    G_CALLBACK (on_checkbutton5FK_toggled),
                    NULL);
  g_signal_connect ((gpointer) checkbutton6FK, "toggled",
                    G_CALLBACK (on_checkbutton6FK_toggled),
                    NULL);
  g_signal_connect ((gpointer) button_retourner3FK, "clicked",
                    G_CALLBACK (on_button_retourner3FK_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_valider2FK, "clicked",
                    G_CALLBACK (on_button_valider2FK_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Modifer_utilisateur, Modifer_utilisateur, "Modifer_utilisateur");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, entry6, "entry6");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, entry7, "entry7");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, entry8, "entry8");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, spinbutton2, "spinbutton2");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, label18, "label18");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, radiobutton3FK, "radiobutton3FK");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, radiobutton4FK, "radiobutton4FK");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, checkbutton4FK, "checkbutton4FK");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, checkbutton5FK, "checkbutton5FK");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, checkbutton6FK, "checkbutton6FK");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, label19, "label19");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, label20, "label20");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, label21, "label21");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, label22, "label22");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, label23, "label23");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, label25, "label25");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, label24, "label24");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, label26, "label26");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, button_retourner3FK, "button_retourner3FK");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, image8, "image8");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, label27, "label27");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, button_valider2FK, "button_valider2FK");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, image9, "image9");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, label28, "label28");
  GLADE_HOOKUP_OBJECT (Modifer_utilisateur, combobox2, "combobox2");

  return Modifer_utilisateur;
}

GtkWidget*
create_Rechercher_utilisateur (void)
{
  GtkWidget *Rechercher_utilisateur;
  GtkWidget *fixed5;
  GtkWidget *label29;
  GtkWidget *entry9;
  GtkWidget *label31;
  GtkWidget *button_retourner4FK;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image11;
  GtkWidget *label32;
  GtkWidget *button_okFK;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label30;

  Rechercher_utilisateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Rechercher_utilisateur), _("Rechercher un utilisateur"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (Rechercher_utilisateur), fixed5);

  label29 = gtk_label_new (_("Entrer l'indentifant de l'utilisateur"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed5), label29, 96, 72);
  gtk_widget_set_size_request (label29, 616, 64);

  entry9 = gtk_entry_new ();
  gtk_widget_show (entry9);
  gtk_fixed_put (GTK_FIXED (fixed5), entry9, 216, 208);
  gtk_widget_set_size_request (entry9, 352, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry9), 8226);

  label31 = gtk_label_new ("");
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 192, 368);
  gtk_widget_set_size_request (label31, 536, 72);

  button_retourner4FK = gtk_button_new ();
  gtk_widget_show (button_retourner4FK);
  gtk_fixed_put (GTK_FIXED (fixed5), button_retourner4FK, 144, 552);
  gtk_widget_set_size_request (button_retourner4FK, 232, 48);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (button_retourner4FK), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image11 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox11), image11, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox11), label32, FALSE, FALSE, 0);

  button_okFK = gtk_button_new ();
  gtk_widget_show (button_okFK);
  gtk_fixed_put (GTK_FIXED (fixed5), button_okFK, 624, 208);
  gtk_widget_set_size_request (button_okFK, 138, 46);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (button_okFK), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label30 = gtk_label_new_with_mnemonic (_("Ok"));
  gtk_widget_show (label30);
  gtk_box_pack_start (GTK_BOX (hbox10), label30, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_retourner4FK, "clicked",
                    G_CALLBACK (on_button_retourner4FK_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_okFK, "clicked",
                    G_CALLBACK (on_button_okFK_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Rechercher_utilisateur, Rechercher_utilisateur, "Rechercher_utilisateur");
  GLADE_HOOKUP_OBJECT (Rechercher_utilisateur, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Rechercher_utilisateur, label29, "label29");
  GLADE_HOOKUP_OBJECT (Rechercher_utilisateur, entry9, "entry9");
  GLADE_HOOKUP_OBJECT (Rechercher_utilisateur, label31, "label31");
  GLADE_HOOKUP_OBJECT (Rechercher_utilisateur, button_retourner4FK, "button_retourner4FK");
  GLADE_HOOKUP_OBJECT (Rechercher_utilisateur, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Rechercher_utilisateur, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Rechercher_utilisateur, image11, "image11");
  GLADE_HOOKUP_OBJECT (Rechercher_utilisateur, label32, "label32");
  GLADE_HOOKUP_OBJECT (Rechercher_utilisateur, button_okFK, "button_okFK");
  GLADE_HOOKUP_OBJECT (Rechercher_utilisateur, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Rechercher_utilisateur, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Rechercher_utilisateur, image10, "image10");
  GLADE_HOOKUP_OBJECT (Rechercher_utilisateur, label30, "label30");

  return Rechercher_utilisateur;
}

GtkWidget*
create_Supprimer_utilisateur (void)
{
  GtkWidget *Supprimer_utilisateur;
  GtkWidget *fixed6;
  GtkWidget *label33;
  GtkWidget *entry10;
  GtkWidget *button_valider3FK;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image13;
  GtkWidget *label35;
  GtkWidget *button_retourner5FK;
  GtkWidget *alignment12;
  GtkWidget *hbox12;
  GtkWidget *image12;
  GtkWidget *label34;

  Supprimer_utilisateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Supprimer_utilisateur), _("Supprimer un utilisateur"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (Supprimer_utilisateur), fixed6);

  label33 = gtk_label_new (_("Enter l'ID de l'utilisateur \303\240 supprimer"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed6), label33, 136, 160);
  gtk_widget_set_size_request (label33, 576, 48);

  entry10 = gtk_entry_new ();
  gtk_widget_show (entry10);
  gtk_fixed_put (GTK_FIXED (fixed6), entry10, 264, 272);
  gtk_widget_set_size_request (entry10, 320, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry10), 8226);

  button_valider3FK = gtk_button_new ();
  gtk_widget_show (button_valider3FK);
  gtk_fixed_put (GTK_FIXED (fixed6), button_valider3FK, 450, 400);
  gtk_widget_set_size_request (button_valider3FK, 300, 40);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (button_valider3FK), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image13 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox13), image13, FALSE, FALSE, 0);

  label35 = gtk_label_new_with_mnemonic (_("Valider"));
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox13), label35, FALSE, FALSE, 0);

  button_retourner5FK = gtk_button_new ();
  gtk_widget_show (button_retourner5FK);
  gtk_fixed_put (GTK_FIXED (fixed6), button_retourner5FK, 50, 400);
  gtk_widget_set_size_request (button_retourner5FK, 300, 40);

  alignment12 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment12);
  gtk_container_add (GTK_CONTAINER (button_retourner5FK), alignment12);

  hbox12 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (alignment12), hbox12);

  image12 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_box_pack_start (GTK_BOX (hbox12), image12, FALSE, FALSE, 0);

  label34 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label34);
  gtk_box_pack_start (GTK_BOX (hbox12), label34, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) button_valider3FK, "clicked",
                    G_CALLBACK (on_button_valider3FK_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_retourner5FK, "clicked",
                    G_CALLBACK (on_button_retourner5FK_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Supprimer_utilisateur, Supprimer_utilisateur, "Supprimer_utilisateur");
  GLADE_HOOKUP_OBJECT (Supprimer_utilisateur, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (Supprimer_utilisateur, label33, "label33");
  GLADE_HOOKUP_OBJECT (Supprimer_utilisateur, entry10, "entry10");
  GLADE_HOOKUP_OBJECT (Supprimer_utilisateur, button_valider3FK, "button_valider3FK");
  GLADE_HOOKUP_OBJECT (Supprimer_utilisateur, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Supprimer_utilisateur, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Supprimer_utilisateur, image13, "image13");
  GLADE_HOOKUP_OBJECT (Supprimer_utilisateur, label35, "label35");
  GLADE_HOOKUP_OBJECT (Supprimer_utilisateur, button_retourner5FK, "button_retourner5FK");
  GLADE_HOOKUP_OBJECT (Supprimer_utilisateur, alignment12, "alignment12");
  GLADE_HOOKUP_OBJECT (Supprimer_utilisateur, hbox12, "hbox12");
  GLADE_HOOKUP_OBJECT (Supprimer_utilisateur, image12, "image12");
  GLADE_HOOKUP_OBJECT (Supprimer_utilisateur, label34, "label34");

  return Supprimer_utilisateur;
}

GtkWidget*
create_confirmation (void)
{
  GtkWidget *confirmation;
  GtkWidget *fixed7;
  GtkWidget *label36;

  confirmation = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (confirmation), _("confirmation"));

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (confirmation), fixed7);

  label36 = gtk_label_new (_("L'utilisateur est bien supprimer"));
  gtk_widget_show (label36);
  gtk_fixed_put (GTK_FIXED (fixed7), label36, 64, 168);
  gtk_widget_set_size_request (label36, 472, 40);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (confirmation, confirmation, "confirmation");
  GLADE_HOOKUP_OBJECT (confirmation, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (confirmation, label36, "label36");

  return confirmation;
}

GtkWidget*
create_nbr_niveau (void)
{
  GtkWidget *nbr_niveau;
  GtkWidget *fixed8;
  GtkWidget *hseparator1;
  GtkWidget *hseparator2;
  GtkWidget *vseparator1;
  GtkWidget *label42;
  GtkWidget *label5annerFK;
  GtkWidget *label4annerFK;
  GtkWidget *label3annerFK;
  GtkWidget *label2annerFK;
  GtkWidget *button_retourner10FK;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label43;
  GtkWidget *label1annerFK;

  nbr_niveau = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (nbr_niveau), _("etudiants par niveau"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (nbr_niveau), fixed8);

  hseparator1 = gtk_hseparator_new ();
  gtk_widget_show (hseparator1);
  gtk_fixed_put (GTK_FIXED (fixed8), hseparator1, 88, 152);
  gtk_widget_set_size_request (hseparator1, 16, 16);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (fixed8), hseparator2, 200, 192);
  gtk_widget_set_size_request (hseparator2, 16, 16);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_fixed_put (GTK_FIXED (fixed8), vseparator1, 256, 128);
  gtk_widget_set_size_request (vseparator1, 16, 16);

  label42 = gtk_label_new (_("Nombre d'etudiant par niveau"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed8), label42, 232, 32);
  gtk_widget_set_size_request (label42, 496, 64);

  label5annerFK = gtk_label_new ("");
  gtk_widget_show (label5annerFK);
  gtk_fixed_put (GTK_FIXED (fixed8), label5annerFK, 64, 608);
  gtk_widget_set_size_request (label5annerFK, 752, 72);

  label4annerFK = gtk_label_new ("");
  gtk_widget_show (label4annerFK);
  gtk_fixed_put (GTK_FIXED (fixed8), label4annerFK, 96, 464);
  gtk_widget_set_size_request (label4annerFK, 704, 120);

  label3annerFK = gtk_label_new ("");
  gtk_widget_show (label3annerFK);
  gtk_fixed_put (GTK_FIXED (fixed8), label3annerFK, 72, 376);
  gtk_widget_set_size_request (label3annerFK, 720, 88);

  label2annerFK = gtk_label_new ("");
  gtk_widget_show (label2annerFK);
  gtk_fixed_put (GTK_FIXED (fixed8), label2annerFK, 80, 256);
  gtk_widget_set_size_request (label2annerFK, 680, 88);

  button_retourner10FK = gtk_button_new ();
  gtk_widget_show (button_retourner10FK);
  gtk_fixed_put (GTK_FIXED (fixed8), button_retourner10FK, 112, 704);
  gtk_widget_set_size_request (button_retourner10FK, 192, 48);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (button_retourner10FK), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label43 = gtk_label_new_with_mnemonic (_("Retourner"));
  gtk_widget_show (label43);
  gtk_box_pack_start (GTK_BOX (hbox14), label43, FALSE, FALSE, 0);

  label1annerFK = gtk_label_new ("");
  gtk_widget_show (label1annerFK);
  gtk_fixed_put (GTK_FIXED (fixed8), label1annerFK, 88, 152);
  gtk_widget_set_size_request (label1annerFK, 712, 80);

  g_signal_connect ((gpointer) button_retourner10FK, "clicked",
                    G_CALLBACK (on_button_retourner10FK_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (nbr_niveau, nbr_niveau, "nbr_niveau");
  GLADE_HOOKUP_OBJECT (nbr_niveau, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (nbr_niveau, hseparator1, "hseparator1");
  GLADE_HOOKUP_OBJECT (nbr_niveau, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (nbr_niveau, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (nbr_niveau, label42, "label42");
  GLADE_HOOKUP_OBJECT (nbr_niveau, label5annerFK, "label5annerFK");
  GLADE_HOOKUP_OBJECT (nbr_niveau, label4annerFK, "label4annerFK");
  GLADE_HOOKUP_OBJECT (nbr_niveau, label3annerFK, "label3annerFK");
  GLADE_HOOKUP_OBJECT (nbr_niveau, label2annerFK, "label2annerFK");
  GLADE_HOOKUP_OBJECT (nbr_niveau, button_retourner10FK, "button_retourner10FK");
  GLADE_HOOKUP_OBJECT (nbr_niveau, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (nbr_niveau, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (nbr_niveau, image14, "image14");
  GLADE_HOOKUP_OBJECT (nbr_niveau, label43, "label43");
  GLADE_HOOKUP_OBJECT (nbr_niveau, label1annerFK, "label1annerFK");

  return nbr_niveau;
}

