/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *Bienvenue;
  GtkWidget *Ajouter_utilisateur;
  GtkWidget *Afficher_utilisatuer;
  GtkWidget *Modifer_utilisateur;
  GtkWidget *Rechercher_utilisateur;
  GtkWidget *Supprimer_utilisateur;
  GtkWidget *confirmation;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  Bienvenue = create_Bienvenue ();
  gtk_widget_show (Bienvenue);
  Ajouter_utilisateur = create_Ajouter_utilisateur ();
  gtk_widget_show (Ajouter_utilisateur);
  Afficher_utilisatuer = create_Afficher_utilisatuer ();
  gtk_widget_show (Afficher_utilisatuer);
  Modifer_utilisateur = create_Modifer_utilisateur ();
  gtk_widget_show (Modifer_utilisateur);
  Rechercher_utilisateur = create_Rechercher_utilisateur ();
  gtk_widget_show (Rechercher_utilisateur);
  Supprimer_utilisateur = create_Supprimer_utilisateur ();
  gtk_widget_show (Supprimer_utilisateur);
  confirmation = create_confirmation ();
  gtk_widget_show (confirmation);

  gtk_main ();
  return 0;
}

